### ISSUE TITLE
Higher print resolution

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#1191]
Use an higher print resolution when no WMS is available.

**Comment by jaykayone** [comment]
the main case where people complain is printing mymaps layers over a topo map.
these are WMS layers BUT mapserver accepts the DPI setting.

we should offer a higher resolution print unless there are arcgis wms layers involved. probably needs a datamodel update though ?

**Comment by jaykayone** [comment]
another idea for the future would be to use the arcgis rest mapping api rather than WMS for the arcgis layers. this supports the dpi setting

**Comment by jaykayone** [comment]
there is the sharpness problem (dpi) but also which zoom level to take (eg at print scale 1:20'000)

**Comment by geoportallux** [comment]
this has again been brought up in a ticket, we should already use 300 dpi if no WMS is present, so we can satisty all the users that do only print a background map.
We should check though if setting 300 dpi is enough or if we have to change the config of the print server so that it uses the more detailled tile level rather than the less detailled one
