### ISSUE TITLE
Layers order

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#1641]
Hi @pgiraud, 

We try to demonstrate with a simple example that our GeoAPI can be used together with OL3. 
[here](http://apps.geoportail.lu/exemple_api/apiv3_demo.html#example16)

Example16 doesn't work as expected due to the fact that bgLayer is not a real background layer. 
As API only adds the background layer when information is received from the webservice, that means the layer created by OL3 is added before into the map, and is displayed below the background. 

What do you think about this problem ? 
thanks,

**Comment by pgiraud** [comment]
Indeed, because the load of layers (background or not) in the API is done asynchronously, the call to `addLayer` on the OL3 map is done first.
What we could do is provide a `ready` event on the `lux.Map`. It would then be possible to register to this event and do any action on the map when it is triggered. This way we would ensure that the layers are already loaded before we add a new one.
I currently don't see any other good solution. Playing with indexes would lead up to complex code in my opinion.

**Comment by pgiraud** [comment]
Oh. Actually I see an other solution. Since we extend the `OL3.Map` we can override the `addLayer` method as well. It would then be as simple as waiting for layers promise to be resolved before we do the job.

@rmichaelis what do you prefer?

**Comment by rmichaelis** [comment]
The second one sounds good.
