### ISSUE TITLE
Recherche unifiée [lux]

### ISSUE THREAD

**Issue by sbrunner** [Geoportail-Luxembourg/geoportailv3#40]
* [x] Conception [lux]
* [x] Processus mise à jour des index [lux]
* [x] Processus de déploiement [lux]
* [x] Composant [lux]
* [x] Composant ngeo [c2c]

Nous avons décidé dans https://github.com/Geoportail-Luxembourg/geoportailv3/issues/235 que Camptocamp travaillait sur un composant de recherche dans ngeo.

Restant c2c 01/03/2015 : 3j
Restant c2c 01/04/2015 : 0.5j

**Comment by elemoine** [comment]
Pourrions-nous revoir ensemble les specs de la recherche ? L'utilisateur va donc pouvoir saisir n'importe quel texte dans le champ de recherche… Quels sont les différents types de résultats qui lui sont alors proposés ? Et quelles sont les actions effectuées par le composant de recherche quand un résultat est sélectionné par l'utilisateur ? J'ai commencé à travailler sur le composant client et j'ai besoin de connaître l'ensemble des use-cases/scénarios. Thx.

**Comment by elemoine** [comment]
Ma branche ngeo pour ce travail sur le search est ici : https://github.com/camptocamp/ngeo/compare/master...elemoine:search. L'exemple `search` est visible ici : http://erilem.net/ngeo/search/search.html. Pour le moment, après sélection d'une suggestion par l'utilisateur, j'ajoute une feature à la carte et je recentre la carte sur cette feature.

**Comment by jaykayone** [comment]
C'est déjà un bon début.
Du point de vue fonctionnel, je pense que nous pouvons recopier à 95% ce qui a été fait dans geoadmin:

![screen shot 2015-03-04 at 13 30 33](https://cloud.githubusercontent.com/assets/1518019/6483558/c3dc9310-c272-11e4-8f71-8cbeee2c64c4.png)
95% parce que je ne veux pas le hover et je veux pouvoir navigeur avec les flèches du clavier dans la liste des résultats proposés

Par contre, je viens de discuter avec Patrick, en fonction des types de résultats renvoyés, il y aura d'autres actions à faire, p.ex. ajout de feature pour un feature, ajout de layer pour un layer, ouverture d'une page cms si résultat CMS etc.

Nous nous voulons et ne pouvons pas tout prévoir aujourd'hui. C'est pourquoi il faut un moyen générique dans ngeo qui permet de définir l'action à déclencher en fonction du type de résultat, p.ex une fonction de callback qui peut être définie dans le projet.

Un autre point qu'on voit dans geoadmin est que le type de résultat influence la représentation du résultat dans la liste (p.ex. le bouton "i" pour les couches. Donc il faut aussi une notion de template qui peut être défini par type de résultat.

For the typeahead settings, we'd prefer to use a rateLimitWait of 100 instead of 300. Do you want to expose the parameter or do you want to set it to 100 by default in ngeo?

**Comment by petzlux** [comment]
Aussi reste a discuter la division entre le résultat autocomplete qui contient pas les geométries, et un call spécifique à la sélection d'un résultat qui renvoie la géométrie (et autres données spécifiques)

**Comment by elemoine** [comment]
> Aussi reste a discuter la division entre le résultat autocomplete qui contient pas les geométries, et un call spécifique à la sélection d'un résultat qui renvoie la géométrie (et autres données spécifiques)

Désolé, je ne comprends pas ce que tu veux dire ici.

**Comment by elemoine** [comment]
@jaykayone Merci. Je vais faire en sorte que l'action après sélection d'une suggestion soit configurable par l'application.

**Comment by jaykayone** [comment]
@petzlux fait référence à la discussion ici: https://github.com/Geoportail-Luxembourg/geoportailv3/issues/169 (commentaire de stéphane d'il y a 29 jours)

**Comment by elemoine** [comment]
Pour info, je viens d'ouvrir un pull request pour le composant `search` de ngeo : https://github.com/camptocamp/ngeo/pull/187. Il y a surement encore des choses à faire, mais c'est un début. Quand ce pull request sera mergé je suggère qu'on mette en place ce composant dans l'application pour identifier les problèmes et les manques.

**Comment by petzlux** [comment]
Oui, je vais m'en occuper !

**Comment by elemoine** [comment]
https://github.com/camptocamp/ngeo/pull/187 a été mergé.

**Comment by petzlux** [comment]
cf #362

**Comment by jaykayone** [comment]
est-ce que ce ticket peut être fermé?

**Comment by elemoine** [comment]
À noter qu'il reste deux checkbox non cochées dans la description de l'issue.

**Comment by petzlux** [comment]
Discuter pendant la telco
