### ISSUE TITLE
Url shortener - check if shorturl exists already for given longurl

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#487]
the url shortener creates different short links for the same long link.
it should look if the long url already has a short url in the db and it should return that one instead

**Comment by petzlux** [comment]
this is an upstream c2cgeoportal issue in the controller. can this be fixed @sbrunner ?

**Comment by elemoine** [comment]
> the url shortener creates different short links for the same long link

We've just discussed this, and we wonder if this is really a problem, because the probability of requesting a short link for a long link for which a short link has already been created is low. And doing a look-ups for already-created shortlinks would require creating an index in the database.

So can't we just create a new short link each time? What do you think?

**Comment by jaykayone** [comment]
can be discussed.
no need to address this now, can be done later

**Comment by rmichaelis** [comment]
This could be a problem when sharing an url with crosshair=true in permalink. 
Each time someone opens the shared-link a new one is generated.

**Comment by jaykayone** [comment]
indeed

**Comment by petzlux** [comment]
Indeed indeed!

**Comment by jaykayone** [comment]
At the moment I will create a database job that deletes short links that have never been clicked after 30 days

**Comment by elemoine** [comment]
:rocket:
