### ISSUE TITLE
print scales

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#489]
print scales should be the following:
1500, 2500, 5000, 10000, 15000, 20000, 25000, 50000, 80000, 100000, 125000, 200000, 250000, 400000

Please pay attention to the scale vs webmercator problem.

what's more is that in geoportalv2 the scales can vary according to the theme. (print_scales key in theme metadata)

**Comment by elemoine** [comment]
> what's more is that in geoportalv2 the scales can vary according to the theme. (print_scales key in theme metadata)

Should this be implemented in v3 as well?

**Comment by jaykayone** [comment]
yes please

**Comment by elemoine** [comment]
See https://github.com/Geoportail-Luxembourg/geoportailv3/pull/516.

So with #516 we use the current theme's print scales, so I think your comment saying that "print scales should the following: …" doesn't hold anymore. Is that correct?

What about the "pay attention to the scale vs webmercator problem"? Could you please be more specific about that? Thanks.

**Comment by jaykayone** [comment]
you are right for the first part, although we could take that array as fallback if no scales are defined in the theme metadata

the scale vs mercator problem is that due to the fact that webmercator meters are factor 1.5 to luref meters we choose to plot the scalebar in luref rather than in webmercator. the scale choosen for print should be a luref scale too and not a webmercator one

**Comment by elemoine** [comment]
> you are right for the first part, although we could take that array as fallback if no scales are defined in the theme metadata

The themes that I get as an anonymous user all have print scales. Are there private themes with no print scales? I can add fallback print scales if you think it's necessary.

> the scale vs mercator problem is that due to the fact that webmercator meters are factor 1.5 to luref meters we choose to plot the scalebar in luref rather than in webmercator. the scale choosen for print should be a luref scale too and not a webmercator one

But do I need to do something about this? I mean: can I just use the print scales specified in the theme configuration?

**Comment by jaykayone** [comment]
After the migration, they all have print-scales but I'd prefer to have a fallback to be sure.

Regarding the webmercator issue, I think that there is something to do, yes.
You certainly remember that when measuring distances we had to use spherical meters rather than webmercator meters to get correct distances. to have a correct scalebar, we have to specify another coordsys than webmercator.

In this case of the print I think that something has to be done to calculate the extent rectangle using spherical meters or in LUREF. I don't know how your code works in this case, I only wanted to stress this as it has been an issue everywhere else

**Comment by elemoine** [comment]
> Regarding the webmercator issue, I think that there is something to do, yes.
> You certainly remember that when measuring distances we had to use spherical meters rather than webmercator meters to get correct distances. to have a correct scalebar, we have to specify another coordsys than webmercator.
> 
> In this case of the print I think that something has to be done to calculate the extent rectangle using spherical meters or in LUREF. I don't know how your code works in this case, I only wanted to stress this as it has been an issue everywhere else

It is still not very clear to me. It'd be great if you could show me what doesn't work as expected.

**Comment by jaykayone** [comment]
![screen shot 2015-06-05 at 14 28 00](https://cloud.githubusercontent.com/assets/1518019/8005916/277628a4-0b8f-11e5-914e-d804aa9fbd34.png)
![screen shot 2015-06-05 at 14 27 42](https://cloud.githubusercontent.com/assets/1518019/8005917/27780912-0b8f-11e5-9c45-fae2ad40fed4.png)

maybe this helps.

**Comment by sbrunner** [comment]
The map has the same dimensions in the booth pdf ?

**Comment by jaykayone** [comment]
yes. more or less

**Comment by jaykayone** [comment]
geoportail v2: 762x440
geoportail v3: 715x395

**Comment by sbrunner** [comment]
It's not enough deference to explain that ...

**Comment by jaykayone** [comment]
that's my point....

**Comment by pgiraud** [comment]
So, we analysed the problem with Eric.

Here's our conclusion:

In the v2, we're working with a local projection (EPSG:2169). Local projection are well suited for measurements and scale computation since they usually respect distance (and sometimes areas).
In v3, it was chosen to use the webmercator projection. This projection is really useful to display the whole world and makes it easy to work with other map tiles providers (OSM, Bing, etc...). However, it's wrong and bad to work with scales with this projection.
While (in OpenLayers) the scale line adapts to the latitude and reacts when panning to north or south, the scale chooser doesn't. The scale chooser considers that the resolution is correct and completely relies on it. But it's in most cases is wrong, unless you're close to the equator.
This means that, even before printing anything, the map displays different things in v2 and v3 for the same scale and this is directly due to the map projection. You can compare the 2 screenshots for which the chosen scale is 1:15'000 though the N6 line is much longer in V3 (on the screen).

![screenshot from 2015-06-09 11 19 53](https://cloud.githubusercontent.com/assets/319774/8054672/b9b7ee10-0e9a-11e5-8307-1f65dcfe7360.png)
![screenshot from 2015-06-09 11 21 59](https://cloud.githubusercontent.com/assets/319774/8054676/bffef516-0e9a-11e5-8b53-6d519c17cb40.png)


Options:
 - completely remove any use of scales from application,
 - adapt scales by applying a ratio so that it approximately match what we had in v2. We'll still have a possible distortion between north and south.
 - print the maps in a local projection which respects distance thus scales,
 - stop using webmercator.

**Comment by jaykayone** [comment]
* completely remove any use of scales from application => not possible
* adapt scales by applying a ratio so that it approximately match what we had in v2. We'll still have a possible distortion between north and south. => could be a solution
* print the maps in a local projection which respects distance thus scales => there is (currently) no wmts in LUREF
* stop using webmercator. => too late ?


What about using the same hack for scale calculation than for distance measurements ? (geodetic measurements?)

**Comment by pgiraud** [comment]
> What about using the same hack for scale calculation than for distance measurements ? (geodetic measurements?)

This would mean change the value displayed in the scale chooser when the map is moved down or up? Pretty impossible.

**Comment by jaykayone** [comment]
The scale chooser has a fake value that is shown anyway. I don't see why this could not be faked even more.

I was rather talking about calculating the size of the extent rectangle ..

**Comment by elemoine** [comment]
I started working on that issue: https://github.com/Geoportail-Luxembourg/geoportailv3/compare/elemoine_print-rectangle-scale. But I'm not done yet…
