### ISSUE TITLE
searching for lines

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#668]
searching for a river (eg "Alzette) does not correctly zoom onto the polyline.

auto completion is quite weird too for alzette

the result is shown when I type "alz" but as soon as I type "Alze" it is gone

**Comment by elemoine** [comment]
Again, Alzette (hydro) is a `GeometryCollection` rather than a `LineString` (or `MultiLineString`) in the GeoJSON response. See http://devv3.geoportail.lu/main/wsgi/fulltextsearch?limit=5&query=Alz&callback=jQuery111309967113130260259_1436199490572&_=1436199490574. This is the reason `view.fit` doesn't work. (This is also the reason printing would not work.)

Is returning a `GeometryCollection` intentional?

**Comment by jaykayone** [comment]
@petzlux can you check this please?

**Comment by petzlux** [comment]
@jaykayone as this is an issue caused upstream by geometrycollection objects in the Postgis table, waiting for you to fix this before doing an import.

**Comment by jaykayone** [comment]
database is updated
